### 
POST http://localhost:9999/clientes/2/transacoes HTTP/1.1
content-type: application/json

{
    "valor": 200,
    "tipo" : "c",
    "descricao" : "descricao"
}

###
GET http://localhost:9999/clientes/2/extrato HTTP/1.1
content-type: application/json


###
GET http://localhost:9999/ HTTP/1.1
content-type: application/json
