### 
POST http://localhost:3000/clientes/2/transacoes HTTP/1.1
content-type: application/json

{
    "valor": 200,
    "tipo" : "c",
    "descricao" : "descricao"
}

###
GET http://localhost:3000/clientes/2/extrato HTTP/1.1
content-type: application/json
